name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install latest nightly
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - name: Build
              run: cargo build --verbose
