name: Rust

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Update
              run: rustup default nightly && rustup update
            - name: Build
              run: cargo build +nightly --verbose
            - name: Run tests
              run: cargo test +nightly --verbose
